site_name: Master GeoPython
site_url: https://geopython.rottengrapes.tech
theme:
  name: material
  palette:
    primary: requirements
  # logo: assets/images/logo.png
  icon:
    logo: material/language-python
  favicon: assets/images/logo.png
  features:
    - navigation.footer
    - content.code.copy
    - navigation.tracking


nav:
  - index.md
  - Introduction:
    - intro-to-python/installation.md
    - Setup Python Environment: intro-to-python/setup-env.md
    - Python Packages: intro-to-python/intro-to-packages.md
    - Set Variables: intro-to-python/variables.md
    - Making List : intro-to-python/list.md
    - Sets and Tuple : intro-to-python/sets-tuple.md
    - Making Dictionary : intro-to-python/dictionary.md
    - Loop through data : intro-to-python/loops.md
    - Creating Conditions : intro-to-python/conditions.md
    - Creating Functions : intro-to-python/functions.md
    - Using Modules : intro-to-python/modules.md
    - Debugging in Python : intro-to-python/debugging.md
    - Object Oriented Programming : intro-to-python/oop.md
  - Advance Python:
    - Numpy :
      - Introduction to Numpy : advance-python/numpy/numpy_intro.md
      - List in Numpy : advance-python/numpy/numpy_creating_list.md
      - Indexing in Numpy : advance-python/numpy/numpy_indexing.md
      - Numpy reshaping : advance-python/numpy/numpy_reshaping.md
      - Numpy Split : advance-python/numpy/numpy_split.md
    - Pandas :
      - Introduction to Pandas : advance-python/pandas/pandas_intro.md
      - Reading & writing data : advance-python/pandas/pandas_create_df.md
      - Cleaning & transforming data : advance-python/pandas/pandas_cleaning.md
      - Indexing & advanced selection: advance-python/pandas/pandas_indexing.md
      - Group operations: advance-python/pandas/pandas_grouping.md
      - Dealing with time series : advance-python/pandas/pandas_time_series.md
    - Matplotlib : 
        - Introduction : advance-python/matplotlib/introduction.md
        - Basics of plots : advance-python/matplotlib/make_plots.md
        - Customizing plots : advance-python/matplotlib/customize_plots.md
        - Working with multiple plots : advance-python/matplotlib/multiple_plots.md
        - Advanced Visualizations : advance-python/matplotlib/advanced_visualization.md
      
  - Vector Analysis: 
      - Spatial Relations : vector-analysis/spatial_relations.md
      - Creating GIS Data in Python from Scratch : vector-analysis/creating_gis_data.md
      - Low Level Vector Access: vector-analysis/low_level_vector_access.md
      - Accessing OSM data using OSMnx : vector-analysis/osmnx.md
      - Attribute Query using Geopandas : vector-analysis/attribute_query.md
      - Spatial Query using Geopandas : vector-analysis/spatial_operations.md
      - Advance spatial operations : vector-analysis/advanced_spatial_operations.md
  - Raster Analysis :
    - Introduction to Raster Data : raster-analysis/introduction_to_raster_data.md
    - Reading Raster Files in Python : raster-analysis/reading_raster_files.md
    - Understanding Raster Geometry and CRS : raster-analysis/understanding_raster_geometry_crs.md
    - Raster Math and Band Operations : raster-analysis/raster_math_and_band_operations.md
    - Clipping and Masking Rasters : raster-analysis/clipping_and_masking_rasters.md
    - Resampling, Reprojecting, and Mosaicking : raster-analysis/resampling_reprojecting_mosaicking.md
    - Raster Zonal Statistics : raster-analysis/raster_zonal_statistics.md
    - Terrain and Elevation Analysis : raster-analysis/terrain_elevation_analysis.md
    - Working with Time-Series Raster Data : raster-analysis/working_with_timeseries_raster_data.md
    - Reading from Cloud and Web Sources : raster-analysis/reading_from_cloud_and_web_sources.md
    - Automating Raster Workflows : raster-analysis/automating_raster_workflows.md
      
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/squidfunk/

copyright: Copyright &copy; 2020 - 2026 Rotten Grapes Private Limited

plugins:
  - search
  - social
  - tags

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
